This chapter introduces functions in Python Numpy to explain basic elements used in Linear Algebra and their definitions. We will explain how to create and use vectors and matrices through examples.

Let’s start with some basic definitions:

![image](images/scalar-vector-matrix-tensor.png)
* A scalar is a single number
* A vector is an array of numbers.
* A matrix is a 2-D array
* A tensor is a n-dimensional array with n>2

Conventions used:
* scalars are written in lowercase and italics. For instance: n
* vectors are written in lowercase, italics and bold type. For instance: x
* matrices are written in uppercase, italics and bold. For instance: X

In [1]:
import numpy as np
from matplotlib import pyplot as plt

Scalar

In [7]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [14]:
mean = 0 
variance = 1
x= np.random.normal(loc = mean, scale= np.sqrt(variance), size=20)
print(x)

[-1.88832536 -0.7438648  -0.2080013  -0.22359357 -0.8391845   0.64569513
 -0.21489617  0.78432344 -0.28346833 -0.4848904  -1.57806806 -0.22521527
 -0.82075589  1.13542258 -0.32774215  1.14406792  1.54891821  1.14858492
  0.11604535 -0.94341641]


In [ ]:
Matrix

In [8]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
A = np.random.randint(160,180,(3,5))
print(A)
print(A.T)

[[173 175 164 176 176]
 [173 171 179 177 167]
 [170 163 176 164 178]]
[[173 173 170]
 [175 171 163]
 [164 179 176]
 [176 177 164]
 [176 167 178]]


Special Matrices

In [21]:
A = np.ones((3,2))
A

In [26]:
B = np.zeros((3,2))
B

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [27]:
C = A + B
C

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [29]:
C = A + 5
C

array([[6., 6.],
       [6., 6.],
       [6., 6.]])

Tensor

In [31]:
T = np.array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])
print(T.shape)
print(T)

(3, 3, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]


In [32]:
T_1 = T * 2
T_1

array([[[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]],

       [[22, 24, 26],
        [28, 30, 32],
        [34, 36, 38]],

       [[42, 44, 46],
        [48, 50, 52],
        [54, 56, 58]]])